# Generated by Django 6.0 on 2025-12-09 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_remove_company_twilio_phone_numbers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_connection', to='companies.company')),
            ],
            options={
                'db_table': 'quickbooks_connections',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('records_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='quickbooks_integration.quickbooksconnection')),
            ],
            options={
                'db_table': 'quickbooks_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickBooksAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=100)),
                ('account_sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='quickbooks_integration.quickbooksconnection')),
            ],
            options={
                'db_table': 'quickbooks_accounts',
                'unique_together': {('connection', 'qb_id')},
            },
        ),
        migrations.CreateModel(
            name='QuickBooksTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_id', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('expense', 'Expense'), ('bill', 'Bill'), ('purchase', 'Purchase'), ('journal_entry', 'Journal Entry')], max_length=50)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='quickbooks_integration.quickbooksconnection')),
            ],
            options={
                'db_table': 'quickbooks_transactions',
                'unique_together': {('connection', 'qb_id', 'transaction_type')},
            },
        ),
    ]
