# Generated by Django 6.0 on 2025-12-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_id', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('raw_data', models.JSONField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='quickbooks_integration.quickbooksconnection')),
            ],
            options={
                'db_table': 'quickbooks_bills',
                'unique_together': {('connection', 'qb_id')},
            },
        ),
        migrations.CreateModel(
            name='QuickBooksCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='quickbooks_integration.quickbooksconnection')),
            ],
            options={
                'db_table': 'quickbooks_customers',
                'unique_together': {('connection', 'qb_id')},
            },
        ),
        migrations.CreateModel(
            name='QuickBooksInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_id', models.CharField(max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('raw_data', models.JSONField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='quickbooks_integration.quickbooksconnection')),
            ],
            options={
                'db_table': 'quickbooks_invoices',
                'unique_together': {('connection', 'qb_id')},
            },
        ),
        migrations.CreateModel(
            name='QuickBooksPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_id', models.CharField(max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='quickbooks_integration.quickbooksconnection')),
            ],
            options={
                'db_table': 'quickbooks_payments',
                'unique_together': {('connection', 'qb_id')},
            },
        ),
        migrations.CreateModel(
            name='QuickBooksVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='quickbooks_integration.quickbooksconnection')),
            ],
            options={
                'db_table': 'quickbooks_vendors',
                'unique_together': {('connection', 'qb_id')},
            },
        ),
    ]
