# Generated by Django 5.2.7 on 2025-10-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='twilio_phone_numbers',
        ),
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='softdelete',
            field=models.BooleanField(default=False),
        ),
    ]
